membuat hello.txt
okyFaishal/fosan-tugas-1-git pull request #1
Opened 2022-02-19 11:14 UTC by okyFaishal

requested a review

2022-02-19 11:32 UTC, r-ijal requested changes

2022-02-19 11:32 UTC, r-ijal commented on hello.txt
> +hai
Ganti jadi "halo Fosan"

2022-02-19 11:43 UTC, okyFaishal commented on hello.txt
> +hai
ok

2022-02-20 08:56 UTC, okyFaishal commented on hello.txt
> +hai
sudah saya ganti

2022-02-20 08:57 UTC, okyFaishal commented on hello.txt
> +hai
> Ganti jadi "halo Fosan"

sudah

2022-02-21 06:21 UTC, r-ijal approved these changes
oke, silahkan di merge

2022-02-21 09:59 UTC, merged